completed kata nc-news6 with test
Damini212/nc-news pull request #6
Opened 2023-06-27 13:14 UTC by Damini212

2023-06-27 13:35 UTC, Slyose reviewed
Great job so far. I've left a couple comments to look at to perfect this ticket, feel free to resubmit a PR after you've made any improvements

2023-06-27 13:35 UTC, Slyose commented on __tests__/nc-news6.test.js
> +        console.log(comments);
Don't forget to take out console logs before your PR!

2023-06-27 13:35 UTC, Slyose commented on __tests__/nc-news6.test.js
> +  });
This does work for the first comment - but it'd be a stronger test to go through all the comments and makes sure they have these properties with the right data types. toMatchObject or expect.objectContaining could help us with this!

2023-06-27 15:29 UTC, amrutha-chil commented on __tests__/nc-news6.test.js
> +        console.log(comments);
Done.

2023-06-27 15:29 UTC, Damini212 commented on __tests__/nc-news6.test.js
> +  });
Done.

2023-06-28 07:51 UTC, Damini212 commented on __tests__/nc-news6.test.js
> +        console.log(comments);
removed the console.log

2023-06-28 07:51 UTC, Damini212 commented on __tests__/nc-news6.test.js
> +  });
added toMatchObject

2023-06-28 08:39 UTC, mezzDavies commented on __tests__/nc-news6.test.js
> +        expect(comments[3]).toMatchObject({
This is an improvement however we should do this assertion for every object in the array. Can you think of a way to this forEach of the objects 😉 ? If you can you MUST first assert the length of the array is correct before doing so. Please resubmit when you have done this. 👍

2023-06-28 08:41 UTC, mezzDavies requested changes
Please see my comment below and resubmit when you have added the code 👍

2023-06-28 09:28 UTC, Keb84 approved these changes
Great to see you've made the changes suggested. I've suggested one more test for you. Feel free to add that and then merge when ready 👍

2023-06-28 09:28 UTC, Keb84 commented on __tests__/nc-news6.test.js
> +      });
Another test that would be good here is to check that if the ID is valid but there are no comments it responds with an empty array 💭

2023-06-28 10:34 UTC, merged