Nc news7 completed with test
Damini212/nc-news pull request #7
Opened 2023-06-27 15:09 UTC by Damini212

2023-06-27 15:34 UTC, RichardNeat requested changes
Nice work on this one 🙌 just a few comments below to have a look into please. Could you make those changes and then resubmit please :)

2023-06-27 15:34 UTC, RichardNeat commented on __tests__/nc-news7.test.js
> +  test("should respond with 400 if the body is not provided", () => {
Be careful when copy and pasting our test blocks - we need to ensure we update the test descriptions :)

2023-06-27 15:34 UTC, RichardNeat commented on __tests__/nc-news7.test.js
> +});
Nice work here with these tests Amrutha, I think there's a couple of other scenarios we would consider here.
- Invalid ID
- Valid input body, but the username is not found
- Consider an input body sent over with extra properties, can we ensure that we ignore them appropriately?

2023-06-27 15:34 UTC, RichardNeat commented on models/nc_news7.model.js
> +      if (!rows[0]) {
We may be able to reply on psql to throw an error if the id is not found as this will violate the foreign key restraint where article id references the articles table

2023-06-27 15:34 UTC, RichardNeat commented on models/nc_news7.model.js
> +const findUserByUsername = (username) => {
Same here, as this will also violate the foreign key restraint, psql should throw an error here for us. Try and just run the psql query in both cases of article id not found and username not found (testing for both) and see what happens. A good process to be follow is to be reactive, allowing psql to handle the error if it's going to, then only if it doesn't throw an error, when we expected one, do we then need to consider some custom error handling.

2023-06-28 07:47 UTC, Damini212 commented on models/nc_news7.model.js
> +      if (!rows[0]) {
I have removed this to allow psql to do the error handling.

2023-06-28 07:48 UTC, Damini212 commented on models/nc_news7.model.js
> +const findUserByUsername = (username) => {
When I remove this function, it gives an error, therefore ,I have kept it to handle any invalid user id.

2023-06-28 07:48 UTC, Damini212 commented on __tests__/nc-news7.test.js
> +  test("should respond with 400 if the body is not provided", () => {
removed the console.log

2023-06-28 07:48 UTC, Damini212 commented on __tests__/nc-news7.test.js
> +});
added the tests.

2023-06-28 07:50 UTC, Damini212 commented on __tests__/nc-news7.test.js
> +  test("should respond with 400 if the body is not provided", () => {
changed the description of the test.

2023-06-28 08:14 UTC, NRMSMITH requested changes
PSQL errors need an error handler :)

2023-06-28 08:14 UTC, NRMSMITH commented on models/nc_news7.model.js
> +const findUserByUsername = (username) => {
To handle this - really you should be able to create a psql error handler - using the err.code that is giving. Catch the error, pass it to the error handlers and then having a look at the error code (use a .only on the test and console.log(err.code)) :)

2023-06-28 10:22 UTC, Damini212 commented on models/nc_news7.model.js
> +const findUserByUsername = (username) => {
added the error handler and removed the extra code.

2023-06-28 11:06 UTC, EddTheDuck approved these changes
Seems you have addressed previous feedback.

Your file structure isn't great however and would mean nothing to anyone outside of Northoders. I would recommend taking some time and consolodating your files so you don't have a file per ticket.

2023-06-28 11:06 UTC, EddTheDuck commented on errorHandlingMiddleware.js
> +  if (error instanceof DatabaseError) {
Interesting way of doing it, however it would be better to use the specific error code :)

2023-06-29 12:59 UTC, merged